### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by vpresnyak** [ayaanhossain/ViennaRNA#3]
Hi!

I've been trying to get ViennaRNA to install on a clean Ubuntu 20.04 installation, and it doesn't seem to be working out for me:

`pip install ViennaRNA` leads to a long error message that culminates in this:

```
    ....
    Making install in Python
    make[2]: Entering directory '/tmp/pip-install-vufg5ioo/ViennaRNA/ViennaRNA-2.5.0/interfaces/Python'
      GEN      RNA/__pycache__/__init__.cpython-38.pyc
      GEN      RNA/__pycache__/__init__.cpython-38.opt-1.pyc
    make[3]: Entering directory '/tmp/pip-install-vufg5ioo/ViennaRNA/ViennaRNA-2.5.0/interfaces/Python'
     /usr/bin/mkdir -p '/usr/lib/python3.8/dist-packages/RNA'
    /usr/bin/mkdir: cannot create directory ‘/usr/lib/python3.8/dist-packages’: Permission denied
    make[3]: *** [Makefile:770: install-pkgpyexecDATA] Error 1
    make[3]: Leaving directory '/tmp/pip-install-vufg5ioo/ViennaRNA/ViennaRNA-2.5.0/interfaces/Python'
    make[2]: *** [Makefile:887: install-am] Error 2
    make[2]: Leaving directory '/tmp/pip-install-vufg5ioo/ViennaRNA/ViennaRNA-2.5.0/interfaces/Python'
    make[1]: *** [Makefile:632: install-recursive] Error 1
    make[1]: Leaving directory '/tmp/pip-install-vufg5ioo/ViennaRNA/ViennaRNA-2.5.0/interfaces'
    make: *** [Makefile:689: install-recursive] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vufg5ioo/ViennaRNA/setup.py", line 105, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-vufg5ioo/ViennaRNA/setup.py", line 102, in run
        self.compile_and_install_ViennaRNA()
      File "/tmp/pip-install-vufg5ioo/ViennaRNA/setup.py", line 96, in compile_and_install_ViennaRNA
        subprocess.check_call('make install', cwd=src_path, shell=True)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'make install' returned non-zero exit status 2.
```

**Comment by ayaanhossain** [comment]
Sorry @vpresnyak I just installed `ViennaRNA` using `pip` on a freshly spun Ubuntu EC2 instance and didn't face any issues. I can't reproduce your error, unfortunately.

Are you able to install `ViennaRNA` from source code manually though? If you don't, then it's likely you don't have the necessary build tools or compilers to install `ViennaRNA` in the first place, so this may not be an issue on `pip`'s end.

If you can install manually though, then it might be a problem with your version of `pip`. Can you try installing `ViennaRNA` from a `miniconda`/`conda` installed `python`, instead of using the one that is pre-installed in the system by default?

**Comment by vpresnyak** [comment]
Thanks for testing, that's strange!

It's indeed a clean Ubuntu 20.04 EC2 instance, and I'm running into this issue. I can confirm that I can get the command to run if I `sudo` the pip call, so it's not likely to be a prereqs issue. This seems unusual, because it suggests a permissions issue; however none of my other pip installed packages run into it.
