### ISSUE TITLE
pip installation error in Windows

### ISSUE THREAD

**Issue by odoluca** [ayaanhossain/ViennaRNA#4]
Hi!

I've been trying to get ViennaRNA to install on Windows 10 with python 3.11.1, and it doesn't seem to be working:

`pip install ViennaRNA ` leads to a long error message that culminates in this:

```
Collecting ViennaRNA
  Using cached ViennaRNA-2.5.0a5.tar.gz (58.0 MB)
  Preparing metadata (setup.py) ... done
Installing collected packages: ViennaRNA
  DEPRECATION: ViennaRNA is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for ViennaRNA ... error
  error: subprocess-exited-with-error

  × Running setup.py install for ViennaRNA did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running install
      C:\Users\odoluca\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      '.' is not recognized as an internal or external command,
      operable program or batch file.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\odoluca\AppData\Local\Temp\pip-install-gwt4cr4d\viennarna_eaf6fd118f9646feba0070b525bc967a\setup.py", line 110, in <module>
          setup(
        File "C:\Users\odoluca\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\odoluca\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\odoluca\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\odoluca\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\odoluca\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\odoluca\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\odoluca\AppData\Local\Temp\pip-install-gwt4cr4d\viennarna_eaf6fd118f9646feba0070b525bc967a\setup.py", line 107, in run
          self.compile_and_install_ViennaRNA()
        File "C:\Users\odoluca\AppData\Local\Temp\pip-install-gwt4cr4d\viennarna_eaf6fd118f9646feba0070b525bc967a\setup.py", line 95, in compile_and_install_ViennaRNA
          subprocess.check_call(cmd, cwd=src_path, shell=True)
        File "C:\Users\odoluca\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command './configure --prefix=C:\Users\odoluca\AppData\Local\Temp\pip-install-gwt4cr4d\viennarna_eaf6fd118f9646feba0070b525bc967a/25bee50a-050a-4ea0-a0c9-81c3f76a8a2f --enable-simd --without-perl --without-doc-pdf --without-doc-html --without-doc --without-tutorial-pdf --without-tutorial-html --without-tutorial --without-cla-pdf --without-cla --without-kinfold --without-forester --without-rnalocmin PYTHON3_DIR=C:\Users\odoluca\AppData\Local\Programs\Python\Python311\Lib\site-packages PYTHON3_EXECDIR=C:\Users\odoluca\AppData\Local\Programs\Python\Python311\Lib\site-packages' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> ViennaRNA

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by ayaanhossain** [comment]
ViennaRNA via this package can only be installed in Linux/MacOS. You may try installing Windows Subsystem for Linux (WSL2) and install ViennaRNA inside that?
